<a href="https://colab.research.google.com/github/taslimmuhammed/pytorch/blob/main/pytorch_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
torch.__version__

'2.3.0+cu121'

# Tensors

In [6]:
t = torch.tensor([7])
t

tensor([7])

In [7]:
t = torch.tensor([[1,2,3],
                  [4,5,6]])
t.ndim

2

In [8]:
t.shape

torch.Size([2, 3])

# Random matrix

In [10]:
r = torch.rand(3,4)
r

tensor([[0.8520, 0.2499, 0.5456, 0.7092],
        [0.3827, 0.5048, 0.2385, 0.8975],
        [0.8847, 0.1294, 0.9416, 0.8626]])

In [11]:
z = torch.zeros(3,3)
o = torch.ones(3,3)
z,o

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

# Arange

In [12]:
a = torch.arange(10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a = torch.arange(1,10,2)
a

tensor([1, 3, 5, 7, 9])

In [14]:
b = torch.zeros_like(a)
b

tensor([0, 0, 0, 0, 0])