<a href="https://colab.research.google.com/github/taslimmuhammed/pytorch/blob/main/pytorch_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
torch.__version__

'2.3.0+cu121'

# Tensors

In [4]:
t = torch.tensor([7])
t

tensor([7])

In [5]:
t = torch.tensor([[1,2,3],
                  [4,5,6]])
t.ndim

2

In [6]:
t.shape

torch.Size([2, 3])

# Random matrix

In [7]:
r = torch.rand(3,4)
r

tensor([[0.5451, 0.0625, 0.4852, 0.7700],
        [0.2146, 0.5568, 0.4839, 0.5612],
        [0.9817, 0.0140, 0.5695, 0.4900]])

In [8]:
z = torch.zeros(3,3)
o = torch.ones(3,3)
z,o

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

# Arange

In [9]:
a = torch.arange(10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a = torch.arange(1,10,2)
a

tensor([1, 3, 5, 7, 9])

In [11]:
b = torch.zeros_like(a)
b

tensor([0, 0, 0, 0, 0])

# Dtypes

In [12]:
arr = torch.tensor([1,2,3,4],dtype=torch.float32)
arr

tensor([1., 2., 3., 4.])

In [13]:
arr.type(torch.int16)

tensor([1, 2, 3, 4], dtype=torch.int16)

**get the device on which it is runing by t.device**

In [14]:
arr.device

device(type='cpu')

# Mathematical Operations

In [15]:
a = torch.tensor([1,2,3])
a+10

tensor([11, 12, 13])

In [16]:
a*10

tensor([10, 20, 30])

**Dot Product**

In [17]:
a = torch.tensor([[1,2,3]])
b = torch.tensor([[3,4,5]])
a*b

tensor([[ 3,  8, 15]])

In [18]:
%%time
torch.matmul(a,b.T)

CPU times: user 617 µs, sys: 0 ns, total: 617 µs
Wall time: 7.1 ms


tensor([[26]])

# Aggregator Functions

In [19]:
t = torch.arange(1,100,10)
t

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [20]:
t.min(), t.max()

(tensor(1), tensor(91))

A  mean function requires the tensor be of type float

In [21]:
t.type(torch.float32).mean()

tensor(46.)

In [22]:
t.sum()

tensor(460)

# positional min/max

In [23]:
t = torch.tensor([[1,2,3],[4,5,6]])
t.argmin()

tensor(0)

# Reshape, stacking


In [31]:
x = torch.arange(1,10)
x.reshape(-1,3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [32]:
torch.stack([x,x,x], dim=0)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [33]:
torch.stack([x,x,x],dim=1)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

# Squeez, permute

In [35]:
x.squeeze(dim=0)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
x.unsqueeze(dim=1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

**Permute is used to change shape, and switch axis, it gives an alternative view with same memory**

In [39]:

a = torch.rand(4,2,3)
a_permute  = a.permute(1,2,0) # switch axis 0->3, 1->0, 0->3
a_permute.shape

torch.Size([2, 3, 4])